// <auto-generated />
using System;
using LiteratureSolitaire.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LiteratureSolitaire.Infrastructure.Migrations
{
    [DbContext(typeof(LiteratureSolitaireDbContext))]
    [Migration("20251222184116_AddedAuthorsPortraits")]
    partial class AddedAuthorsPortraits
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LiteratureSolitaire.Infrastructure.Data.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Author Identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Author`s Name");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Author`s Photo Path");

                    b.HasKey("Id");

                    b.ToTable("Authors", t =>
                        {
                            t.HasComment("Author");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Димитър Талев",
                            PhotoPath = "/images/authors/dimitar_talev.png"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Алеко Константинов",
                            PhotoPath = "/images/authors/aleko_konstantinov.jpg"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Станислав Стратиев",
                            PhotoPath = "/images/authors/stanislav_stratiev.jpg"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Иван Вазов",
                            PhotoPath = "/images/authors/ivan_vazov.jpg"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Никола Вапцаров",
                            PhotoPath = "/images/authors/nikola_vaptsarov.jpg"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Йордан Радичков",
                            PhotoPath = "/images/authors/yordan_radichkov.jpg"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Христо Ботев",
                            PhotoPath = "/images/authors/hristo_botev.jpg"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Елин Пелин",
                            PhotoPath = "/images/authors/elin_pelin.jpg"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Христо Смирненски",
                            PhotoPath = "/images/authors/hristo_smirnenski.jpg"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Емилиян Станев",
                            PhotoPath = "/images/authors/emilian_stanev.jpg"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Пейо Яворов",
                            PhotoPath = "/images/authors/peyo_yavorov.jpg"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Пенчо Славейков",
                            PhotoPath = "/images/authors/pencho_slaveikov.jpg"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Димчо Дебелянов",
                            PhotoPath = "/images/authors/dimcho_debelqnov.jpg"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Христо Фотев",
                            PhotoPath = "/images/authors/hristo_fotev.jpg"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Петя Дубарова",
                            PhotoPath = "/images/authors/petya_dubarova.jpg"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Атанас Далчев",
                            PhotoPath = "/images/authors/atanas_dalchev.jpg"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Йордан Йовков",
                            PhotoPath = "/images/authors/yordan_yovkov.jpg"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Виктор Пасков",
                            PhotoPath = "/images/authors/viktor_paskov.jpg"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Елисавета Багряна",
                            PhotoPath = "/images/authors/elisaveta_bagryana.jpg"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Борис Христов",
                            PhotoPath = "/images/authors/boris_hristov.jpg"
                        });
                });

            modelBuilder.Entity("LiteratureSolitaire.Infrastructure.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Category Identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Category Name");

                    b.HasKey("Id");

                    b.ToTable("Categories", t =>
                        {
                            t.HasComment("Category");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Родното и чуждото"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Миналото и паметта"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Обществото и властта"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Животът и смъртта"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Природата"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Любовта"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Вярата и надеждата"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Трудът и творчеството"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Изборът и раздвоението"
                        });
                });

            modelBuilder.Entity("LiteratureSolitaire.Infrastructure.Data.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Genre Identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Genre Name");

                    b.HasKey("Id");

                    b.ToTable("Genres", t =>
                        {
                            t.HasComment("Genre");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Роман"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Фейлетон"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Сатирична комедия на абсурда"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Ода"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Стихотворение"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Разказ"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Сатира, Алегория"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Повест"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Пантеистичнo стихотворение"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Поема"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Лирическа миниатюра"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Елегия"
                        });
                });

            modelBuilder.Entity("LiteratureSolitaire.Infrastructure.Data.Models.LiteraryDirection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Literary Direction Identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Literary Direction Name");

                    b.HasKey("Id");

                    b.ToTable("LiteraryDirections", t =>
                        {
                            t.HasComment("Literary Direction");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Реализъм"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Романтизъм"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Магически реализъм"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Социален реализъм"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Индивидуализъм"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Символизъм"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Диаболизъм"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Екзистенциализъм"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Модернизъм"
                        });
                });

            modelBuilder.Entity("LiteratureSolitaire.Infrastructure.Data.Models.Work", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Work Identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int")
                        .HasComment("Work Author");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasComment("Work Category");

                    b.Property<string>("Characters")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Work Characters");

                    b.Property<int>("GenreId")
                        .HasColumnType("int")
                        .HasComment("Work Genre");

                    b.Property<int>("LiteraryDirectionId")
                        .HasColumnType("int")
                        .HasComment("Work Literary Direction");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Work Title");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("GenreId");

                    b.HasIndex("LiteraryDirectionId");

                    b.ToTable("Works", t =>
                        {
                            t.HasComment("Work");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            CategoryId = 1,
                            Characters = "Стоян Глаушев, Султана, Лазар, Катерина, Рафе Клинче, Климент Бенков, Божана, Стойка Нунева, Аврам Немтур",
                            GenreId = 1,
                            LiteraryDirectionId = 1,
                            Title = "\"Железният светилник\""
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            CategoryId = 1,
                            Characters = "Бай Ганьо, Гочоолу, Дочоолу, Данко Харсъзина, Гуньо Адвокатина/Гуньо Келеперчиков",
                            GenreId = 2,
                            LiteraryDirectionId = 1,
                            Title = "\"Бай Ганьо журналист\""
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 3,
                            CategoryId = 1,
                            Characters = "Бяла Врана, Жена с проблем, Жена символ, Директор на театър, бай Цончо, Йовчо, Цончето, Печо, баба Кера, Извънземното, Георги",
                            GenreId = 3,
                            LiteraryDirectionId = 1,
                            Title = "\"Балкански синдром\""
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 4,
                            CategoryId = 2,
                            Characters = "Паисий, лирически говорител",
                            GenreId = 4,
                            LiteraryDirectionId = 2,
                            Title = "\"Паисий\""
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 5,
                            CategoryId = 2,
                            Characters = "Лирически говорител, историята",
                            GenreId = 5,
                            LiteraryDirectionId = 1,
                            Title = "\"История\""
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 6,
                            CategoryId = 2,
                            Characters = "хлебарките, космическият удваник, трите врани, каракачанката, въшкарчето, глиганът, Апостола, папунякът, щъркелът, лисицата, Емилиян Станев, Григор Вачков, Методи Андонов",
                            GenreId = 1,
                            LiteraryDirectionId = 3,
                            Title = "\"Ноев ковчег\""
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 7,
                            CategoryId = 3,
                            Characters = "Соломон, лирически говорител",
                            GenreId = 5,
                            LiteraryDirectionId = 1,
                            Title = "\"Борба\""
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 8,
                            CategoryId = 3,
                            Characters = "Андрешко, съдия-изпълнител, повествователят",
                            GenreId = 6,
                            LiteraryDirectionId = 4,
                            Title = "\"Андрешко\""
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 9,
                            CategoryId = 3,
                            Characters = "Дяволът, плебеят",
                            GenreId = 7,
                            LiteraryDirectionId = 1,
                            Title = "\"Приказка за стълбата\""
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 7,
                            CategoryId = 4,
                            Characters = "Лирически герой/Аз, либето",
                            GenreId = 5,
                            LiteraryDirectionId = 2,
                            Title = "\"До моето първо либе\""
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 4,
                            CategoryId = 4,
                            Characters = "Лирически говорител, загиналите воини, България",
                            GenreId = 5,
                            LiteraryDirectionId = 1,
                            Title = "\"Новото гробище над Сливница\""
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 10,
                            CategoryId = 4,
                            Characters = "Иво Обретенович, Елисавета, Никола Козичката, полковникът",
                            GenreId = 8,
                            LiteraryDirectionId = 1,
                            Title = "\"Крадецът на праскови\""
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 4,
                            CategoryId = 5,
                            Characters = "лирически Аз, природата",
                            GenreId = 9,
                            LiteraryDirectionId = 1,
                            Title = "\"При Рилския манастир\""
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 11,
                            CategoryId = 5,
                            Characters = "лирически говорител, Ваньо селянчето",
                            GenreId = 10,
                            LiteraryDirectionId = 6,
                            Title = "\"Градушка\""
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 12,
                            CategoryId = 5,
                            Characters = "лирически говорител, белостволите буки",
                            GenreId = 11,
                            LiteraryDirectionId = 5,
                            Title = "\"Спи езерото\""
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 13,
                            CategoryId = 6,
                            Characters = "лирически Аз/влюбеният мъж, обречената жена",
                            GenreId = 12,
                            LiteraryDirectionId = 6,
                            Title = "\"Аз искам да те помня така\""
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 14,
                            CategoryId = 6,
                            Characters = "лирически Аз/влюбеният мъж, обичаната жена",
                            GenreId = 5,
                            LiteraryDirectionId = 1,
                            Title = "\"Колко си хубава!\""
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 15,
                            CategoryId = 6,
                            Characters = "влюбената девойка/лирическият говорител, обичаният",
                            GenreId = 5,
                            LiteraryDirectionId = 1,
                            Title = "\"Посвещение\""
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 8,
                            CategoryId = 7,
                            Characters = "Монката, дядо Захари",
                            GenreId = 6,
                            LiteraryDirectionId = 4,
                            Title = "\"Спасова могила\""
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 16,
                            CategoryId = 7,
                            Characters = "лирическият Аз, Господ",
                            GenreId = 5,
                            LiteraryDirectionId = 7,
                            Title = "\"Молитва\""
                        },
                        new
                        {
                            Id = 21,
                            AuthorId = 5,
                            CategoryId = 7,
                            Characters = "лирическият Аз, Животът",
                            GenreId = 5,
                            LiteraryDirectionId = 8,
                            Title = "\"Вяра\""
                        },
                        new
                        {
                            Id = 22,
                            AuthorId = 8,
                            CategoryId = 8,
                            Characters = "Лазар Дъбака, дядо Корчан, Христина",
                            GenreId = 6,
                            LiteraryDirectionId = 4,
                            Title = "\"Ветрената мелница\""
                        },
                        new
                        {
                            Id = 23,
                            AuthorId = 17,
                            CategoryId = 8,
                            Characters = "Сали Яшар, Джапар, Шакире",
                            GenreId = 6,
                            LiteraryDirectionId = 1,
                            Title = "\"Песента на колелетата\""
                        },
                        new
                        {
                            Id = 24,
                            AuthorId = 18,
                            CategoryId = 8,
                            Characters = "Виктор Георг/дядо Георги, Божения, Марсен, Франета, Ванда",
                            GenreId = 8,
                            LiteraryDirectionId = 9,
                            Title = "\"Баладa за Георг Хених\""
                        },
                        new
                        {
                            Id = 25,
                            AuthorId = 11,
                            CategoryId = 9,
                            Characters = "лирическият Аз",
                            GenreId = 5,
                            LiteraryDirectionId = 6,
                            Title = "\"Две души\""
                        },
                        new
                        {
                            Id = 26,
                            AuthorId = 19,
                            CategoryId = 9,
                            Characters = "потомката - лирическият Аз",
                            GenreId = 5,
                            LiteraryDirectionId = 6,
                            Title = "\"Потомка\""
                        },
                        new
                        {
                            Id = 27,
                            AuthorId = 20,
                            CategoryId = 9,
                            Characters = "лирическият говорител/Аз",
                            GenreId = 10,
                            LiteraryDirectionId = 8,
                            Title = "\"Честен кръст\""
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LiteratureSolitaire.Infrastructure.Data.Models.Work", b =>
                {
                    b.HasOne("LiteratureSolitaire.Infrastructure.Data.Models.Author", "Author")
                        .WithMany("Works")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LiteratureSolitaire.Infrastructure.Data.Models.Category", "Category")
                        .WithMany("Works")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LiteratureSolitaire.Infrastructure.Data.Models.Genre", "Genre")
                        .WithMany("Works")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LiteratureSolitaire.Infrastructure.Data.Models.LiteraryDirection", "LiteraryDirection")
                        .WithMany("Works")
                        .HasForeignKey("LiteraryDirectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Category");

                    b.Navigation("Genre");

                    b.Navigation("LiteraryDirection");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LiteratureSolitaire.Infrastructure.Data.Models.Author", b =>
                {
                    b.Navigation("Works");
                });

            modelBuilder.Entity("LiteratureSolitaire.Infrastructure.Data.Models.Category", b =>
                {
                    b.Navigation("Works");
                });

            modelBuilder.Entity("LiteratureSolitaire.Infrastructure.Data.Models.Genre", b =>
                {
                    b.Navigation("Works");
                });

            modelBuilder.Entity("LiteratureSolitaire.Infrastructure.Data.Models.LiteraryDirection", b =>
                {
                    b.Navigation("Works");
                });
#pragma warning restore 612, 618
        }
    }
}
